# Project language
language: php

# Allows use container-based infrastructure
sudo: false

# Start mysql service
services:
    - mysql

# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache/files

php:
  # aliased to a recent 7.0.x version
  - 7.1
  # aliased to a recent hhvm version
  - hhvm
  # aliased to a nightly version
  - nightly

# Matrix to test in every php version
matrix:
  # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: nightly

# Define an environment variable
env:
  - SYMFONY_VERSION="3.3.*" DB=mysql

# Update composer
before-install:
  - composer self-update

before_script:
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer install
  - mysql -e 'create database symfony;'
  - php bin/console doctrine:migrations:migrate  --no-interaction
  # loading data for phpunit and codeconcept tests
  - php bin/console doctrine:fixtures:load --fixtures ./src/AppBundle/DataFixtures -n --env=test
  # Directory used by codecoverage
  - mkdir -p build/logs

script:
  - if [ "$TRAVIS_PHP_VERSION" == "7.1" ]; then travis_wait 40 php vendor/phpunit/phpunit/phpunit --coverage-clover build/logs/clover.xml; fi
  - if [ "$TRAVIS_PHP_VERSION" != "7.1" ]; then php vendor/phpunit/phpunit/phpunit; fi
  # Server must be started for codeconcept tests.
  - php bin/console server:start
  - php vendor/bin/codecept run
  - php bin/console server:stop

after_success:
  - if [ "$TRAVIS_PHP_VERSION" == "7.1" ]; then php vendor/bin/coveralls -v; fi

notifications:
  email:
    - alexandre.tranchant@gmail.com
