# Project language
language: php

services:
  - postgresql

sudo: true

addons:
  postgresql: "9.6"

php:
  # aliased to a recent 7.0.x version
  - 7.1
  # aliased to a recent hhvm version
  - hhvm
  # aliased to a nightly version
  - nightly

# Matrix to test in every php version
matrix:
  # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: nightly

# Define an environment variable
env:
  - SYMFONY_VERSION="3.3.*" DB=postgresql

# Update composer
before-install:
  - composer self-update

before_script:
  # Testing to reinstall it
  - sudo apt-get install postgresql-9.6-postgis-2.3 postgis -y -q
  # Parameters are copied
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  # Database creation
  - psql -c 'create database symfony;' -U postgres
  # Postgis extension creation
  - psql -U postgres -c "create extension postgis"
  # - psql -c 'CREATE EXTENSION postgis_topology;' -U postgres -d symfony
  # excution de composer
  - composer install
  # Database migration to current version
  - php bin/console doctrine:migrations:migrate  --no-interaction
  # loading data for phpunit and codecept tests
  - php bin/console doctrine:fixtures:load --fixtures ./src/AppBundle/DataFixtures -n --env=test
  # updates zxt_log_entries to set username to Dawny
  - php bin/console doctrine:query:sql "UPDATE ext_log_entries SET username='Dawny' where username is null"
  # Directory used by codecoverage
  - mkdir -p build/logs

script:
  # Tests de versions
  - psql --version
  - psql -d symfony -c 'SELECT PostGIS_version();' -U postgres
  # Phpunit and codecoveralls
  - if [ "$TRAVIS_PHP_VERSION" == "7.1" ]; then travis_wait 40 php vendor/phpunit/phpunit/phpunit --coverage-clover build/logs/clover.xml; fi
  - if [ "$TRAVIS_PHP_VERSION" != "7.1" ]; then php vendor/phpunit/phpunit/phpunit; fi
  - if [ "$TRAVIS_PHP_VERSION" == "7.1" ]; then php vendor/bin/coveralls -v; fi
  # Server must be started for codeconcept tests.
  - php bin/console server:start
  - php vendor/bin/codecept run -c src/AppBundle/codeception.yml
  - php bin/console server:stop
  - cat src/AppBundle/Tests/_output/*
  - ls var/data/
  - ls var/logs/


notifications:
  email:
    - alexandre.tranchant@gmail.com
