app:
    resource: '@AppBundle/Controller/'
    type: annotation

# https://symfony.com/doc/master/bundles/FOSUserBundle/index.html#step-6-import-fosuserbundle-routing-files
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
